version: "3"

services:
  postgres:
    image: "postgres:13.3"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/schedule
      - gems:/gems

volumes:
  postgres:
  gems:
