default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
 
 
development:
  <<: *default
  database: Schedule_development
  password: postgres
 
 
test:
  <<: *default
  database: Schedule_test
  password: postgres
 
 
production:
  <<: *default
  database: Schedule_production
  password: <%= ENV['POSTGRES_PASSWORD'] %>